language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -q install liblz4-dev libsnappy-dev zlib1g-dev

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck VERBOSE=1
